// Fix for ONNX Runtime SAL annotations with MinGW
#pragma once
#ifndef _SAL_H_
#define _SAL_H_
#define _In_
#define _In_opt_
#define _In_z_
#define _In_opt_z_
#define _In_reads_(x)
#define _In_reads_opt_(x)
#define _In_reads_bytes_(x)
#define _In_reads_bytes_opt_(x)
#define _Inout_
#define _Inout_opt_
#define _Inout_updates_bytes_all_(x)
#define _Out_
#define _Out_opt_
#define _Out_writes_(x)
#define _Out_writes_opt_(x)
#define _Out_writes_bytes_(x)
#define _Out_writes_bytes_opt_(x)
#define _Outptr_
#define _Outptr_opt_
#define _Outptr_result_maybenull_
#define _Outptr_opt_result_maybenull_
#define _Outptr_result_buffer_(x)
#define _Outptr_opt_result_buffer_(x)
#define _Outptr_result_bytebuffer_(x)
#define _Outptr_opt_result_bytebuffer_(x)
#define _COM_Outptr_
#define _COM_Outptr_opt_
#define _COM_Outptr_result_maybenull_
#define _COM_Outptr_opt_result_maybenull_
#define _Ret_maybenull_
#define _Ret_notnull_
#define _Success_(x)
#define _Check_return_
#define _Must_inspect_result_
#define _Printf_format_string_
#define _Null_terminated_
#define _NullNull_terminated_
#define _Frees_ptr_opt_
#define _Frees_ptr_
#define _Pre_notnull_
#define _Pre_maybenull_
#define _Post_notnull_
#define _Post_maybenull_
#define _Acquires_lock_(x)
#define _Releases_lock_(x)
#define _Requires_lock_held_(x)
#define _Guarded_by_(x)
#endif
